language: php

php:
  - 7.1
  - 7.2
  - 7.3

env: 
  matrix: 
    - COMPOSER_FLAG="--prefer-lowest"
    - COMPOSER_FLAG=""

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS}

script: 
  - vendor/bin/phpunit